// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rnfjwoolxgpgtvjddric.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJuZmp3b29seGdwZ3R2amRkcmljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE3ODQ5MDIsImV4cCI6MjA1NzM2MDkwMn0.fztsyv02PeweQnThPro9xc4tmEtkeKKc9PQk--n1s6g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);